version: '3.4'

services: 
  chatbox-client: 
   build: ./ChatBoxClient
   depends_on: 
     - chatbox-server
   image: chatbox-client
   ports: 
     - "4200:80"
  chatbox-server: 
    build: ./ChatBoxServer/ChatBox
    image: chatbox-server
    ports: 
      - "5000:80"